# Generated by Django 2.2.5 on 2019-09-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=140)),
                ('admission_date', models.DateField()),
                ('date_birth', models.DateField()),
                ('general_record', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresses', models.ManyToManyField(related_name='employee', to='address.Address', verbose_name='address')),
            ],
            options={
                'verbose_name': 'employee',
                'db_table': 'employee',
            },
        ),
    ]
