# Generated by Django 2.2.5 on 2019-09-13 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='adresses',
        ),
        migrations.AddField(
            model_name='employee',
            name='adresses',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='address.Address', verbose_name='address'),
            preserve_default=False,
        ),
    ]
