# Generated by Django 2.2.5 on 2019-09-13 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0002_auto_20190913_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='company.Company', verbose_name='company'),
            preserve_default=False,
        ),
    ]
