# Generated by Django 2.2.5 on 2019-09-13 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_employee_company'),
        ('product', '0004_product_company'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=140)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to='company.Company', verbose_name='company')),
                ('employees', models.ManyToManyField(related_name='service', to='employee.Employee', verbose_name='employees')),
                ('products', models.ManyToManyField(related_name='service', to='product.Product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'service',
                'db_table': 'service',
            },
        ),
    ]
