# Generated by Django 2.2.5 on 2019-09-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('business_name', models.CharField(max_length=140)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresses', models.ManyToManyField(related_name='provider', to='address.Address', verbose_name='address')),
            ],
            options={
                'verbose_name': 'provider',
                'db_table': 'provider',
            },
        ),
    ]
