# Generated by Django 2.2.5 on 2019-09-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=140)),
            ],
            options={
                'verbose_name': 'product',
                'db_table': 'product',
            },
        ),
    ]
