# Generated by Django 2.2.5 on 2019-09-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
        ('product', '0002_product_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ManyToManyField(related_name='product', to='provider.Provider', verbose_name='provider'),
        ),
    ]
