# Generated by Django 2.2.5 on 2019-09-13 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('product', '0003_auto_20190913_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='company.Company', verbose_name='company'),
            preserve_default=False,
        ),
    ]
